# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: latex-project-template 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "latex-project-template".freeze
  s.version = "0.0.5".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Takayuki YAMAGUCHI".freeze]
  s.date = "2025-03-28"
  s.description = "Create LaTeX project with git from template, which uses latexmk.".freeze
  s.email = "d@ytak.info".freeze
  s.executables = ["latex-project-template".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/latex-project-template",
    "initial_files/component/math_preamble.tex",
    "initial_files/component/rakefile_common.erb",
    "initial_files/template/default/Rakefile.erb",
    "initial_files/template/default/__DOT__gitignore",
    "initial_files/template/default/__PROJECT__.tex.erb",
    "initial_files/template/japanese/Rakefile.erb",
    "initial_files/template/japanese/__IMPORT__",
    "initial_files/template/japanese/__PROJECT__.tex.erb",
    "initial_files/template/japanese/latexmkrc",
    "initial_files/variable/profile.yaml",
    "latex-project-template.gemspec",
    "lib/latex_project_template.rb",
    "lib/latex_project_template/task.rb",
    "spec/latex_project_template_spec.rb",
    "spec/spec_helper.rb",
    "spec/task_spec.rb"
  ]
  s.homepage = "http://github.com/ytaka/latex-project-template".freeze
  s.licenses = ["GPLv3".freeze]
  s.rubygems_version = "3.6.2".freeze
  s.summary = "LaTeX Project Template".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<rspec>.freeze, [">= 2.6.0".freeze])
  s.add_development_dependency(%q<yard>.freeze, [">= 0.7.2".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0".freeze])
  s.add_development_dependency(%q<jeweler>.freeze, [">= 1.6.4".freeze])
  s.add_development_dependency(%q<filename>.freeze, [">= 0.1.0".freeze])
  s.add_development_dependency(%q<user_config>.freeze, [">= 0.0.2".freeze])
  s.add_runtime_dependency(%q<git>.freeze, [">= 1.2.5".freeze])
  s.add_runtime_dependency(%q<filename>.freeze, [">= 0.1.0".freeze])
  s.add_runtime_dependency(%q<user_config>.freeze, [">= 0.0.2".freeze])
end

